spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db1?useSSL=false&useServerPrepStmts=true
    username: root
    password: 990105zz
    driver-class-name: com.mysql.cj.jdbc.Driver

  jdbc:
    template:
      query-timeout: 3

  # 配置mybatis规则、使用MyBatisPlus则此项配置无效
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


